// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminResetUserTilesReducer from "../admin_reset_user_tiles_reducer";
import SetTileColorReducer from "../set_tile_color_reducer";

export type AdminResetUserTilesParams = __Infer<typeof AdminResetUserTilesReducer>;
export type SetTileColorParams = __Infer<typeof SetTileColorReducer>;

